version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /opt/wanted_project:/wanted
    links:
      - db:mysql
    container_name: wanted_web
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
        PORT: 5000
        SECRET_KEY: 'you-will-never-guess'
        DEBUG: 1
        MYSQL_ROOT_PASSWORD: wanted
        DB_USERNAME: root
        DB_PASSWORD: wanted
        DB_HOST: mysql
        DATABASE_NAME: wanteddb
  db:
    image: mysql:5.7
    restart: always
    container_name: wanted_db
    ports:
      - "3306:3306"
    environment:
        MYSQL_PASSWORD: wanted
        MYSQL_ROOT_PASSWORD: wanted
        MYSQL_DATABASE: wanteddb
    volumes:
      - "./init/:/docker-entrypoint-initdb.d/"