"""empty message

Revision ID: c386df11e24b
Revises: 
Create Date: 2021-08-11 07:44:30.943553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c386df11e24b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('Tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('CompanyLang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=50), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['Company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_CompanyLang_name'), 'CompanyLang', ['name'], unique=False)
    op.create_table('CompanyTag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['Company.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['Tag.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_CompanyTag_tag_id'), 'CompanyTag', ['tag_id'], unique=False)
    op.create_table('TagLang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('lang', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['Tag.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TagLang')
    op.drop_index(op.f('ix_CompanyTag_tag_id'), table_name='CompanyTag')
    op.drop_table('CompanyTag')
    op.drop_index(op.f('ix_CompanyLang_name'), table_name='CompanyLang')
    op.drop_table('CompanyLang')
    op.drop_table('Tag')
    op.drop_table('Company')
    # ### end Alembic commands ###
